language: python

deploy:
  provider: pypi
  user: gitcoin
  password:
    secure: "placeholder"
  distributions: "sdist bdist_wheel"
  on:
    tags: true

addons:
  apt:
    update: true

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7

install: pip install .

script:
  - python setup.py test

notifications:
  email: false
